redisclient: 
  image: anapsix/webdis
  links: 
    - ambassador:redis
  ports:
    - 8000:7379

ambassador:
  image: svendowideit/ambassador
  environment: 
    - REDIS_PORT_6379_TCP=tcp://192.168.33.10:6379
  expose:
   - "6379"
